### ISSUE TITLE
JOSE Review: Learning resources for data ethics?

### ISSUE THREAD

**Issue by lechten** [valdanchev/reproducible-data-science-python#10]
This is related to your [JOSE submission](https://github.com/openjournals/jose-reviews/issues/156).

The notebook on data ethics mentions three resources under “Learning resources about the A-level controversy”.  Please add hyperlinks.

**Comment by valdanchev** [comment]
The three missing hyperlinks in section [Learning resources about the A-level controversy](https://valdanchev.github.io/reproducible-data-science-python/notebooks/10_data_ethics.html#learning-resources-about-the-a-level-controversy) are now added.

**Comment by lechten** [comment]
Looks good, thanks!
