### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by TomDonoghue** [valdanchev/reproducible-data-science-python#4]
While exploring the textbook, I noticed some broken links that I'll collect here. 

Image links:
- in `python_data_science_cloud`, the image link to `https://jupyter.org/assets/labpreview.png` no longer resolves, leaving a blank image under "Get started with Jupyter and Colab notebooks"
- in `data_exploration_visualisation`, the image link to `https://inferentialthinking.com/_images/Bootstrap_25_0.png` no longer resolves, and leaves a blank image under the "Bootstrapping for inference" section

File links:
- In the `data_exploration_visualisation` notebook the link for "Sam Lau, Joey Gonzalez, and Deb Nolan. 10.4. Visualization Principles." is broken.
  - The current link is  `https://www.textbook.ds100.org/ch/10/viz_principles.html`, but it looks like the page moved to `https://www.textbook.ds100.org/ch/11/viz_intro.html`

**Comment by valdanchev** [comment]
Many thanks, @TomDonoghue. These are very helpful! Just updated the links.
