### ISSUE TITLE
JOSE Review: Typos, URLs

### ISSUE THREAD

**Issue by lechten** [valdanchev/reproducible-data-science-python#7]
This is related to your [JOSE submission](https://github.com/openjournals/jose-reviews/issues/156).

- In Acknowledgements, a closing parenthesis is missing (after “(BITSS)”?).
- L. 96, “The resource is designed to scaffold reproducible and transparent research workflow”: Should this be “a” workflow or “workflows”?
- The checklist asks for DOIs.  Not all papers have one.  Did you check?  Note that the URL in Lau et al. is not formatted as hyperlink.
- The URL in Guzharina is too long.  It should be broken, maybe at “-”.

**Comment by valdanchev** [comment]
Thank you for the helpful comments, which I have addressed: 
* corrected the typos 
* added DOIs for almost all papers (except for Hagberg et al which does not seem to be available)
* formated the URL in Guzharina to fit

**Comment by lechten** [comment]
I just tried to generate a new PDF [for the JOSE issue](https://github.com/openjournals/jose-reviews/issues/156), which failed, probably due to the subdirectory. Do you know how to do that?

**Comment by valdanchev** [comment]
Many thanks! Just renamed the subdirectory to `paper`, which hopefully solves this; if not, another option would be to place the paper files outside the subdirectory.

**Comment by lechten** [comment]
Thanks! Now there is a [ruby exception](https://github.com/openjournals/jose-reviews/issues/156#issuecomment-1131845312)...

I have no idea whether this is a general issue or related to your paper.

**Comment by lechten** [comment]
Actually, that is probably the ":" in the title.  Maybe replace with emdash? Or quote somehow?

**Comment by valdanchev** [comment]
Totally, thanks, added quotes.

**Comment by lechten** [comment]
Thank you for the update. I asked for the PDF at JOSE...

**Comment by lechten** [comment]
Thank you for your patience. With the new PDF, everything seems fine to me. Closing this.
