### ISSUE TITLE
JOSE Review: Choice of and pointers to Jupyter environments

### ISSUE THREAD

**Issue by lechten** [valdanchev/reproducible-data-science-python#9]
This is related to your [JOSE submission](https://github.com/openjournals/jose-reviews/issues/156).

In Section “Getting started”, MyBinder and Colab are mentioned but their differences remain vague.  Why should students choose what variant?  Afterwards, only links to Colab are provided.  Why?  For the purposes of this paper, a single link to the online textbook might be sufficient.  The textbook could then offer clear guidance concerning the question what notebooks to open when (which is related to issue #6).

Note that on https://valdanchev.github.io/reproducible-data-science-python/end_to_end_data_science_project.html the link [Google Colaboratory](https://valdanchev.github.io/reproducible-data-science-python/(https://colab.research.google.com/notebooks/intro.ipynb#recent=true)) is broken.  I’m confused where students are supposed to switch from the textbook to Jupyter environments.  I suggest to add explicit pointers in that regard.

In addition, “Python for Data Analysis on the Cloud” also mentions this: “Students with no Google account will have an opportunity to access the Jupyter notebook on the cloud via JupyterHub and The Littlest JupyterHub (also known as TLJH) in particular.”  
I do not know what that means.

As the resources also aims to teach ethics issues, I suggest to clarify Colab terms of service: What is tracked by Google for what purposes?

**Comment by valdanchev** [comment]
The differences between MyBinder and Colab are now emphasised in: 
* in the [JOSE paper](https://github.com/valdanchev/reproducible-data-science-python/blob/master/JOSE_paper/paper.md)
* the learning resource website, section [How to get the most of the open learning resource?](https://valdanchev.github.io/reproducible-data-science-python/notebooks/00_textbook_outline.html#how-to-get-the-most-of-the-open-learning-resource) 
* README file in the resource [repository](https://github.com/valdanchev/reproducible-data-science-python#readme) 

Links to notebooks on GitHub, MyBidner, and Colab are provided in a table on the resource [website](https://valdanchev.github.io/reproducible-data-science-python/notebooks/00_textbook_outline.html#how-to-get-the-most-of-the-open-learning-resource) and in the [README file](https://github.com/valdanchev/reproducible-data-science-python#readme). Links are now removed from the paper as suggested. 

The link to [Google Colaboratory](https://colab.research.google.com/notebooks/intro.ipynb#) is now functional on the [website](https://valdanchev.github.io/reproducible-data-science-python/notebooks/01_end_to_end_data_science_project.html#get-started-with-jupyter-colab-notebook). 

References to the Littlest JupyterHub (also known as TLJH) are now removed, they refered to a very early in-class version. 

There are now clear guidance regarding the differences between the resource website and notebooks on GitHub, MyBinder, and Colab. 

Section 'Self-guided learning' in the paper discusses access and user privacy in relation to MyBinder and Colab.

**Comment by lechten** [comment]
Looks good, thanks!
